import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Jaguar's Charity Site",
  description: 'Generated by create next app and developed by Ankur Jaiswal',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script async src="https://cdn.tailwindcss.com"></script>
      </head>
      <body className={String(inter.className) + " w-full h-full"}>{children}</body>
    </html>
  )
}
